// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZWL0FIZ8bbtSscO2Fo9ehMiHtzGixw-4',
    appId: '1:552225823406:web:6d7b09b3e2e336735f6b3f',
    messagingSenderId: '552225823406',
    projectId: 'personal-finance-manager-22200',
    authDomain: 'personal-finance-manager-22200.firebaseapp.com',
    storageBucket: 'personal-finance-manager-22200.firebasestorage.app',
    measurementId: 'G-VP7W4V8KMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2vZgYUczvaQHBp4GolI7aoOk1G_bxm1I',
    appId: '1:552225823406:android:8a52d4ff555cc9975f6b3f',
    messagingSenderId: '552225823406',
    projectId: 'personal-finance-manager-22200',
    storageBucket: 'personal-finance-manager-22200.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWNUlzhFaDW2U12kLl4AOCWX4aBHIcGiE',
    appId: '1:552225823406:ios:f3aa782c9112f2955f6b3f',
    messagingSenderId: '552225823406',
    projectId: 'personal-finance-manager-22200',
    storageBucket: 'personal-finance-manager-22200.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWNUlzhFaDW2U12kLl4AOCWX4aBHIcGiE',
    appId: '1:552225823406:ios:f3aa782c9112f2955f6b3f',
    messagingSenderId: '552225823406',
    projectId: 'personal-finance-manager-22200',
    storageBucket: 'personal-finance-manager-22200.firebasestorage.app',
    iosBundleId: 'com.example.finance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZWL0FIZ8bbtSscO2Fo9ehMiHtzGixw-4',
    appId: '1:552225823406:web:06a9088fcd56d41e5f6b3f',
    messagingSenderId: '552225823406',
    projectId: 'personal-finance-manager-22200',
    authDomain: 'personal-finance-manager-22200.firebaseapp.com',
    storageBucket: 'personal-finance-manager-22200.firebasestorage.app',
    measurementId: 'G-FWYYVCSEQQ',
  );
}
